"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import "../public/icons/fontawesome.css"
import HeadMetaData from "@/components/HeadMetaData";
import CustomLayout from "@/components/CustomLayout";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const queryClient = new QueryClient();

export default function RootLayout({ children }) 
{
  return (
    <html lang="en">
      <HeadMetaData />
      <body className="body-tag">
        <div>
          <QueryClientProvider client={queryClient}>
            <CustomLayout {...{children}}/>
            
            <ReactQueryDevtools />
          </QueryClientProvider>
        </div>
      </body>
    </html>
  );
}
